[package]
name = "app-backend"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["server"]

[workspace.dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }

[dependencies]
server = { version = "0.1.0", path = "server" }
