[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
sea-orm.workspace = true
serde.workspace = true
short-uuid.workspace = true
thiserror.workspace = true
utoipa.workspace = true
uuid.workspace = true
