[package]
name = "interface"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
infra = { version = "0.1.0", path = "../infra" }
measurement = { version = "0.1.0", path = "../context/measurement" }
utoipa.workspace = true
